set PROJ_NAME "RedPACPLL6-20200408"

source make_cores.tcl

# Create the project and import the source files and set all project/file properties
# Create the block design inside of the project this file is autogenerated
source make_V2019.2-RP-PACPLLV6-prj.tcl

puts "Created $design_name"


