set PROJ_NAME RedPACPLL-Vsvn

source make_cores.tcl

# Create the project and import the source files and set all project/file properties
source RedPACPLL-mk_prj_new.tcl

# Create the block design inside of the project this file is autogenerated
source RedPACPLL-mk_bd_new.tcl

set design_name [get_bd_designs]
set proj_dir [get_property directory [current_project]]

puts "Created $design_name"

# Update the blockdiagram
regenerate_bd_layout
save_bd_design

# Create the hdl wrapper files for the block design and add them to the project
make_wrapper -files [get_files $design_name.bd] -top -import

puts "Created bd_design $design_name in project $PROJ_NAME"


close_bd_design [get_bd_designs $design_name]
