.TH GXSM3 "9 Dec 2014"
.SH NAME
\fBgxsm3\fP \- Gnome X Scanning Microscopy Project

.SH SYNOPSIS
.br
.B gxsm3
[\fIOPTION\fR...] [\fIFILE\fR...] [+\fILINE\fR[:\fICOLUMN\fR]]
.br
.B gxsm3
[\fIOPTION\fR...] -

.SH DESCRIPTION
.B gxsm3
is ... build on the GNOME desktop environment.

.B gxsm3
features a flexible plugin system which can be used to dynamically add 
new advanced features to
.B gxsm3
itself.
.LP
.SH OPTIONS
        
.TP
Percy Zahl et. al.

