name: gxsm3
version: '3.52.0-svn'
summary: GXSM -- Gnome X Scanning Microscopy.
description: |
  Multi-channel data acquisition via STM/AFM
  GXSM -- Gnome X Scanning Microscopy.
  .
  Gxsm is a powerful graphical interface for any kind of 2D
  and 3D (multilayered 2D mode) data acquisition methods, 
  especially designed for SPM and SPA-LEED, which are used 
  in surface science. It includes methods for 2D data (of 
  various types: byte, short, long, double) visualization 
  and manipulation. We are currently using it for STM, AFM, 
  SARLS, and SPA-LEED.
  .
  Gxsm is powerful, it is easy to extend via plug-ins, it is
  unlimited in data size... and it is a free and open source 
  software hosted by SourceForge! It is based on the Linux 
  Gtk+/Gnome development environment.
  .
  More details on http://gxsm.sf.net and 
  http://sranger.sf.net or in 
  J. Vac. Sci. Technol. B 28, C4E39 (2010) 
  (doi:10.1116/1.3374719) 

grade: stable
confinement: devmode
base: core18

apps:
  gxsm3:
    command: bin/gxsm3
    extensions: [gnome-3-28]

parts:
  gxsm3:
    plugin: autotools
    autotools-parameter: [--prefix=/snap/gxsm3/current/usr]
    override-pull: |
      snapcraftctl pull
      # Point icon to the correct location
      #sed -i.bak -e 's|Icon=com.github.johnfactotum.Foliate|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.johnfactotum.Foliate.svg|g' data/com.github.johnfactotum.Foliate.desktop.in
    source-type: svn
    source: https://svn.code.sf.net/p/gxsm/svn/trunk/Gxsm-3.0
    build-packages:
      - g++
      - make
      - intltool
      - autotools-dev
      - freeglut3-dev
      - gsettings-desktop-schemas-dev
      - gtk-doc-tools
      - libatk-bridge2.0-dev
      - libcairo2-dev
      - libopencv-dev
      - libfftw3-dev
      - libgail-3-dev
      - libglew-dev
      - libglib2.0-dev
      - libglm-dev
      - libglu1-mesa-dev
      - libgsl-dev
      - libgtk-3-dev
      - libgtksourceview-3.0-dev
      - libpython3.7-dev
      - libnetcdf-dev
      - libnetcdf-c++4-dev
      - libnetcdf-cxx-legacy-dev
      - libnlopt-dev
      - libpopt-dev
      - libquicktime-dev
      - libsoup2.4-dev
      - libxml2-dev
      - mesa-common-dev
      - python3.7
      - python3.7-dev
      - python3-dev
      - python3-gi
      - subversion
      - yelp
      - yelp-tools

    stage-packages:
      - bash
      - libaec0
      - libasn1-8-heimdal
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libcurl3-gnutls
      - libdatrie1
      - libepoxy0
      - libfftw3-double3
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libgl1
      - libglew2.0
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgsl23
      - libgslcblas0
      - libgssapi3-heimdal
      - libgtk-3-0
      - libgtksourceview-3.0-1
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libhdf5-100
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu60
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnetcdf-c++4
      - libnetcdf13
      - libnghttp2-14
      - libopencv-core3.2
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpopt0
      - libpsl5
      - libpython3.8
      - libquicktime2
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsoup2.4-1
      - libsz2
      - libtbb2
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwind0-heimdal
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1

